name: Build and Test JTReg

on:
  push:
    branches-ignore:
        - master

jobs:

  linux-x64:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the source
        uses: actions/checkout@v2
        with:
          path: jtreg
          fetch-depth: 0

      - name: build
        working-directory: jtreg
        shell: bash
        run: sh make/build-all.sh ${JAVA_HOME_8_X64}

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: jtreg
          path: jtreg/build/images/jtreg

      - name: test
        working-directory: jtreg
        shell: bash
        run:
             SKIP_WGET=true
             MAKE_ARGS=test
             HEADLESS=1
             JDK8_HOME=${JAVA_HOME_8_X64}
             sh make/build-all.sh ${JAVA_HOME_8_X64}

